/**
 * ============================================================
 *  PORTFOLIO CONFIGURATION — DO NOT EDIT THIS FILE
 *
 *  Edit  portfolio.config.json  instead.
 *  That file has no code syntax — just fill in your details.
 * ============================================================
 */

import type { ColorPreset, PresetPalette } from "@/lib/themes";
import rawConfig from "../portfolio.config.json";

// Re-export the raw JSON config with proper types applied
export const config = {
  ...rawConfig,
  colorPreset: rawConfig.colorPreset as ColorPreset,
  defaultTheme: rawConfig.defaultTheme as "system" | "light" | "dark",

  // customColors is only needed when colorPreset is "custom".
  // If you use "custom", also add a customColors block to portfolio.config.json.
  customColors: (rawConfig as unknown as { customColors?: PresetPalette })
    .customColors,
};
